config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :goods
  resources :rooms
  resources :buildings

  get '/signup', to: 'users#new'
  resources :users

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/statics', to: 'static_pages#statics'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :logged_in_user, only: %i[home contact]
  before_action :authorize, only: %i[statics]
  def home; end

  def contact

  end

def statics
	
    @topfiveusers = User.includes(:bookings)
    .group("bookings.user_id")
    .pluck("users.name, count(bookings.id)")
    .first(5).last(30.days)
    
    @topfiverooms = Room.includes(:bookings)
    .group("bookings.room_id")
    .pluck("rooms.name, count(bookings.id)")
    .first(5).last(30.days)

  end
 
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Contact</h1>
    <p class="lead"></p>
  </div>
</div>
<div class="container">
<span class="title">
Hi! This app was made for Code Academy III purposes. It's still on progress but suggestions are accepted.
</span>
<h2 class="h2title">Who am I </h2>
<div class="row">
  <div class="col-md-2">
   <%= image_tag("profilepic.jpg", :class => 'profile', :alt => "laura ramos") %>

  </div>
  <div class="col-md-10">
  <p class="paragraph">I'm Laura, a 28 years old developer and multimedia artist, based in Buenos Aires. 
  </p>
  <p class="paragraph">I like cats, 90's music and Chuck Palahniuk books. I work at IBM.</p>
  <p><%= link_to "<home", root_path %></p>
</div>
</div>
</div>

app/views/static_pages/home.html.erb
<div class="main-wrapper background-bee">

  <div class="container no-margin-right more-width">
    <div class="row">
      <div class="col-md-8 col-md-offset-1">
        <div class="pill"></div>
        <h1 class="maintitle">Smarter Rooms</h1>
      </div>


      <div class="col-md-4 login-container">
      <div class="login-buttons">
        <% if logged_in? %>

          <%= link_to "Log out", logout_path, method: :delete, :class => "btn  btn-light"   %>
        <% else %>
        <%= link_to "Sign up now", signup_path, :class => "btn  btn-light"  %>
          <%= link_to "Log in", login_path, :class => "btn  btn-light" %>
        <% end %>
        <%= link_to "contact", contact_path, :class => "btn  btn-light" %>
      </div>
    </div>
    </div>  
  </div>

</div>

app/views/static_pages/statics.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Statics</h1>
    <p class="lead">Free rooms, percent of month occupation and other booking metrics</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-s-12 statics-table">
      <p class="title">Reserved rooms but with no people in </p>
      <table class="table table-dark"> 
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
          </tr>
        </thead>

      <tbody>
        <% @booked_rooms = Room.booked %>
          <%  @booked_rooms.each  do |b| %>
            <% @api = Room.api(b.code) %>
            <% if @api["is_occupied"] == false %>
              <tr >
                <td><%= b.name %></td>
                <td><%= b.code %></td>
              </tr>
              <% end %>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6 col-s-12 statics-table">
      <p class="title">Occupied but with no reservation </p>
      <table class="table table-dark"> 
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
          </tr>
        </thead>

        <tbody>
        <% @free_rooms = Room.free.all %>
          <% @free_rooms.each do |f| %>
          <% @api = Room.api(f.code) %>
          <% if @api["is_occupied"] == true %>
            <tr >
              <td><%= f.name %></td>
              <td><%= f.code %></td>
            </tr>
            <% end %>
        <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

<div class="container graphics-container">
  <div class="row">
    <div class="col-md-6 col-s-12">
      <p class="title text-center">Top 5 users in the last 30 days</p>

      <%= pie_chart @topfiveusers %>
    </div>
    <div class="col-md-6 col-s-12">
      <p class="title text-center">Top 5 booked rooms in the last 30 days</p>

      <%= pie_chart @topfiverooms %>
    </div>
  </div>
</div>