config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :goods
  resources :rooms
  resources :buildings

  get '/signup', to: 'users#new'
  resources :users

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/statics', to: 'static_pages#statics'

end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_one :building

  has_many :roomgoods
  has_many :goods, through: :roomgoods

  has_many :bookings
  has_many :users, through: :bookings
  paginates_per 10


  def self.api(code_room)
    conn = Faraday.new(url: 'https://ca-3-api.mybluemix.net/api/v1/rooms/' + code_room)
    response = conn.get
    data = JSON.parse response.body
  end


  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

 def self.free(time = Time.now)
    booking_room_ids = Booking.time_lapse(time).pluck(:room_id)
    where('id NOT IN (?)', booking_room_ids)
  end

  def self.booked(time = Time.now)
    booking_room_ids = Booking.time_lapse(time).pluck(:room_id)
    where(:id => booking_room_ids)
  end

end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: [:new, :edit, :create, :update, :destroy]
  before_action :authorize, only: [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    #@sarasa = occupied_but_no_booking(:valid_from, :valid_to)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
    @goods = Good.all
  end

  # GET /rooms/1/edit
  def edit
    @goods = Good.all
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:name, :code, :floor, :capacity, good_ids: [])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="container form-container">
<div class="col-md-7">
<div class="card form-card">
<h2 class="title">New Room</h2>



<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :floor %>
    <%= form.text_field :floor %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">

  <%= hidden_field_tag "room[good_ids][]", nil %>
  <%= form.collection_check_boxes :good_ids, Good.all, :id, :name %>

  </div>

  <div class="field">
    <%= form.label :building %>
    <%= form.collection_select(:building_id, Building.all , :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.check_box :is_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

  </div>
  </div>
  </div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid 40-margin">
  <div class="container">
    <h1 class="display-4">Rooms</h1>
    <p class="lead">Where do you want to book a meeting?</p>
  </div>
</div>

<div class="container 40-bottom">
<table class="table table-dark"> 
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Code</th>
      <th scope="col">Floor</th>
      <th scope="col">Capacity</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="3"></th>
      <th scope="col" colspan="3"></th>
      

    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
    <% @api = Room.api(room.code) %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.code %></td>
        <td><%= room.floor %></td>
        <td><%= room.capacity %></td>
        <td class="text-center">  
        <% if @api['is_occupied'] === true %>
        <%=icon  'fas fa-male', class: 'occupance' %>
        <%= @api['estimated_occupants']%>
        <% else %>
        <p class="green">free</p>
        <% end %>
        </td>
        <td><%= link_to 'Book', new_booking_path(room_id: room.id), class: "btn btn-sm btn-primary" %>
        <td><%= link_to 'Show', room %></td>
        <% if current_user.is_admin %>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


        
<% if current_user.is_admin %>
<%= link_to 'New Room', new_room_path %>
<% end %>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @room.code %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Accesories:</strong>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>