config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :goods
  resources :rooms
  resources :buildings

  get '/signup', to: 'users#new'
  resources :users

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/statics', to: 'static_pages#statics'

end

app/views/layouts/_navbar.html.erb
<nav id="navbar" class="navbar fixed-top navbar-dark">

  <div class="mr-auto">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag("bee.svg", :class => 'bee-svg', :alt => "bee logo") %>
  <% end %>
  <%= link_to 'Smarter Rooms', root_path, class: 'navbar-brand'  %>
    <%= link_to 'Rooms', rooms_path, class: 'navbar-brand small-brand first'  %>
  <%= link_to 'My bookings', bookings_path, class: 'navbar-brand small-brand'  %>
  <%= link_to 'Contact', contact_path, class: 'navbar-brand small-brand'  %>
        <% if current_user.is_admin %>


    <%= link_to 'Users', users_path, class: 'navbar-brand small-brand'  %>
    <%= link_to 'Statics', statics_path, class: 'navbar-brand small-brand'  %>
      <% end %>

  </div>


  <div class="search-input">
  <%= form_tag(rooms_path, method: :get, id: 'search-rooms') do %>
    <%= text_field_tag :search, params[:search], type: 'search', placeholder: 'search' %>
    <%= submit_tag ("Search"), class: 'hidden' %>
  <% end %>
  </div>




  <div class="py-2 d-none d-md-inline-block ui pointing dropdown link item ">
  <div class="dropdown">
  <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" >
  <%=icon  'fa fas fa-user-circle', class: 'dropdown icon' %>
  <% if logged_in? %>
              <%=current_user.name%>
            <% end %>
  </button>

  <div class="dropdown-menu dropdown-menu-right">
  <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
  </div>
  </div>
  </div>  
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmarterRooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('bee.svg') %>

  </head>

    <body>
    
      <% if logged_in? %>
			<%= render 'layouts/navbar' %>
      <% end %>
    
        <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>

    <%= yield %>
</html>